name: "IAM Role List"

on:
    push:
        branches:
          - feature/check-role-usage
    workflow_dispatch:

env:
  AWS_REGION: "eu-west-2"
  ENVIRONMENT_MANAGEMENT: ${{ secrets.MODERNISATION_PLATFORM_ENVIRONMENTS }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

defaults:
  run:
    shell: bash

jobs:
    monitor-iam-roles:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

          - name: Set Account Number
            run: echo "ACCOUNT_NUMBER=$(jq -r -e '.modernisation_platform_account_id' <<< $ENVIRONMENT_MANAGEMENT)" >> $GITHUB_ENV

          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
            with:
              role-to-assume: "arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/github-actions"
              role-session-name: githubactionsrolesession
              aws-region: ${{ env.AWS_REGION }}

          - name: Run IAM Script
            run: bash ./scripts/check-role-usage.sh

          - name: Upload Role CSV file
            uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
            with:
              name: role-usage-results
              path: ./ssm-automation-role-report.csv
              retention-days: 5